version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=invoice
      - MARIADB_DATABASE=invoice
      - MARIADB_PASSWORD=root

  myapp:
    tty: true
    image: docker.io/bitnami/laravel:8
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=invoice
      - DB_DATABASE=invoice
      - DB_PASSWORD=root
    depends_on:
      - mariadb
    ports:
      - 80:3000
      - 3000:3001
    volumes:
      - ./:/app
    # privileged: true # Privileged mode could be required to run this container under Windows
